version: "3.8"

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: django_password
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://django_user:django_password@db:5432/django_db
    volumes:
      - .:/app
    command: [ "sh", "-c", "python manage.py migrate && gunicorn myproject.wsgi:application --bind 0.0.0.0:8000 --workers 4" ]

  nginx:
    image: nginx:latest
    restart: always
    depends_on:
      - web
    ports:
      - "80:80"  # Changer de 8080 à 80 pour qu'il serve directement
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  pgdata:
