name: Django CI/CD

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v3

      - name: Installer Docker Compose
        run: |
          sudo apt update
          sudo apt install docker-compose

      - name: Construire et Tester avec Docker Compose
        run: |
          docker-compose build
          docker-compose up -d
          sleep 10
          docker-compose ps
          docker logs $(docker ps --format "{{.Names}}" | grep web)
          docker-compose down

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v3

      - name: Login à Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Construire et Pousser l’image Docker
        run: |
          docker build -t my-django-app .
          docker tag my-django-app mydockerhubusername/my-django-app:latest
          docker push mydockerhubusername/my-django-app:latest

      - name: Déployer l’application avec Docker Compose
        run: |
          docker pull mydockerhubusername/my-django-app:latest
          docker stop my-django-app || true
          docker rm my-django-app || true
          docker run -d -p 8000:8000 --name my-django-app mydockerhubusername/my-django-app:latest
