name: Django CI/CD

on:
  push:
    branches:
      - prod

jobs:
  build:
    if: github.ref == 'refs/heads/prod'
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v3

      - name: Installer Docker Compose
        run: |
          sudo apt update
          sudo apt install docker-compose

      - name: Construire et Tester avec Docker Compose
        run: |
          docker-compose build
          docker-compose up -d
          sleep 10
          docker-compose ps
          docker logs $(docker ps --format "{{.Names}}" | grep web)
          docker-compose down

  deploy:
    needs: build
    if: github.ref == 'refs/heads/prod'  # Ignore dev, exécute seulement sur prod
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v3

      - name: Login à Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin || exit 1

      - name: Construire et Pousser l’image Docker
        run: |
          docker build -t my-django-app .
          docker tag my-django-app ${{ secrets.DOCKER_USERNAME }}/my-django-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-django-app:latest

      - name: Déployer sur le serveur distant via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/my-django-app:latest
            docker stop my-django-app || true
            docker rm my-django-app || true
            docker run -d -p 8000:8000 --name my-django-app ${{ secrets.DOCKER_USERNAME }}/my-django-app:latest
